# Generated by Django 3.2.3 on 2022-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0005_auto_20221003_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, help_text='Название продукта - не более 200 символов', max_length=200, verbose_name='Наименование ингридиента'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='Ingredient_unique'),
        ),
    ]
