# Generated by Django 3.2.3 on 2022-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0011_auto_20221003_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, help_text='Загрузите картинку', null=True, upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
