# Generated by Django 3.2.3 on 2022-10-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0012_alter_recipe_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='IngredientInRecipe_unique'),
        ),
    ]
