# Generated by Django 3.2.3 on 2022-10-11 09:27

import dblogic.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название продукта - не более 200 символов', max_length=200, verbose_name='Наименование ингридиента')),
                ('measurement_unit', models.CharField(help_text='Единица измерения: г, шт и.т.д. Не более 200 символов', max_length=200, verbose_name='Единица измерения ингридиента')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Количество согласно единицам измерения', validators=[django.core.validators.MinValueValidator(1, message='Значение не менее 1')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингридиенты в рецептах',
                'verbose_name_plural': 'Ингридиенты в рецептах',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название блюда', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(default=None, help_text='Загрузите картинку', null=True, upload_to='recipes/images/', verbose_name='Картинка')),
                ('text', models.TextField(help_text='Описание процесса приготовления', verbose_name='Описание')),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение не менее 1')], verbose_name='Время приготовления (в минутах)')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тег для быстрого выбора необходимых рецептов', max_length=200, unique=True, verbose_name='Наименование тега')),
                ('color', models.CharField(help_text='Код цвета в формате #HHHHHH', max_length=7, unique=True, validators=[dblogic.models.validate_hex_color], verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(help_text='^[-a-zA-Z0-9_]+$', max_length=200, unique=True, verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ManyToManyField(help_text='Набор рецептов для списка покупок', related_name='shoppingcart', to='dblogic.Recipe', verbose_name='Добавленные рецепты')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'ordering': ('-id',),
            },
        ),
    ]
