# Generated by Django 3.2.3 on 2022-10-02 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dblogic', '0002_auto_20221003_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Пользователь, который добавил в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='dblogic.recipe', verbose_name='Пользователь')),
                ('user', models.ForeignKey(help_text='Пользователь, который добавил в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Favorite_unique'),
        ),
    ]
