# Generated by Django 3.2.3 on 2022-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0007_auto_20221003_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', upload_to='static/images/', verbose_name='Картинка'),
        ),
    ]
