# Generated by Django 3.2.3 on 2022-10-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0013_ingredientinrecipe_ingredientinrecipe_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингридиент, соотносимый с рецептом', on_delete=django.db.models.deletion.CASCADE, to='dblogic.ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, соотносимый с интридиентом', on_delete=django.db.models.deletion.CASCADE, to='dblogic.recipe', verbose_name='Рецепт'),
        ),
    ]
