# Generated by Django 3.2.3 on 2022-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblogic', '0016_alter_ingredientinrecipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(help_text='Набор рецептов для списка покупок', related_name='shoppingcart', to='dblogic.Recipe', verbose_name='Добавленные рецепты'),
        ),
    ]
